#!/usr/bin/env bash
# Distribute per-branch crush.json across the Kontor.
#
#   ./distribute_crush_config.sh          write the configs
#   ./distribute_crush_config.sh --check  report drift only, change nothing (exit 1 on drift)
#
# Parallel to distribute_manifest.sh. Thomas directs it; a session may run it.
# Never edit a branch's crush.json by hand — it is overwritten without warning.
#
# crush.json cannot carry a comment (the schema sets additionalProperties:false),
# so the "generated" marker lives in the provider's display name, where Crush shows it.

set -euo pipefail

# ---------------------------------------------------------------- configuration
# The classification is instance data and lives outside this repository.
# LOCAL_FIRST : the local model is the default; a hosted one is one keystroke away
# HOSTED      : a hosted model is the default
# READONLY    : the agent may read but not write in these branches
CONF="${KONTOR_CONF:-$HOME/.config/kontor/branches.conf}"
[ -r "$CONF" ] || { echo "no config at $CONF (see tools/kontor.conf.example)" >&2; exit 2; }
. "$CONF"
: "${LOCAL_FIRST:?}" "${HOSTED:?}" "${KONTOR_ROOT:?}"
READONLY=("${READONLY[@]:-}")

# The wrapper reads this to decide which branches default to local.
BRANCH_LIST="$HOME/.config/crush/local-first-branches"

MARK="generated by tools/distribute_crush_config.sh — do not edit here"

local_cfg() {
  local readonly_tools="$1"
  local disabled='' ; [ "$readonly_tools" = yes ] && disabled='
    "disabled_tools": ["edit", "multiedit", "write"],'
  cat <<JSON
{
  "\$schema": "https://charm.land/crush.json",
  "options": {
    "disable_default_providers": true,
    "disable_metrics": true,
    "disable_provider_auto_update": true,$disabled
    "context_paths": ["AGENTS.md"]
  },
  "providers": {
    "hyper": {
      "id": "hyper",
      "name": "Charm Hyper ($MARK)",
      "type": "hyper",
      "base_url": "https://hyper.charm.land/api/v1/fantasy",
      "discover_models": false,
      "models": [
        { "id": "qwen3.8-flash", "name": "Qwen3.8 Flash (guenstig)", "context_window": 1000000,
          "default_max_tokens": 32000, "cost_per_1m_in": 0.15, "cost_per_1m_out": 0.47,
          "cost_per_1m_in_cached": 0, "cost_per_1m_out_cached": 0.016,
          "can_reason": true, "supports_attachments": true },
        { "id": "glm-5.3-flash", "name": "GLM 5.3 Flash (guenstig)", "context_window": 1048576,
          "default_max_tokens": 32000, "cost_per_1m_in": 0.16332, "cost_per_1m_out": 0.5444,
          "cost_per_1m_in_cached": 0, "cost_per_1m_out_cached": 0.0315752,
          "can_reason": true, "supports_attachments": true },
        { "id": "glm-5.3", "name": "GLM 5.3 (stark, teuer)", "context_window": 1048576,
          "default_max_tokens": 32000, "cost_per_1m_in": 1.52432, "cost_per_1m_out": 4.79072,
          "cost_per_1m_in_cached": 0, "cost_per_1m_out_cached": 0.283088,
          "can_reason": true, "supports_attachments": true }
      ]
    },
    "openrouter": {
      "id": "openrouter",
      "name": "OpenRouter free — bewusst zu waehlen ($MARK)",
      "type": "openrouter",
      "base_url": "https://openrouter.ai/api/v1",
      "api_key": "\$(security find-generic-password -s kontor-openrouter -w)",
      "discover_models": false,
      "models": [
        { "id": "thinkingmachines/inkling:free", "name": "Inkling (free, HOSTED)", "context_window": 1048576,
          "default_max_tokens": 16384, "cost_per_1m_in": 0, "cost_per_1m_out": 0,
          "cost_per_1m_in_cached": 0, "cost_per_1m_out_cached": 0,
          "can_reason": true, "supports_attachments": true }
      ]
    },
    "ollama": {
      "id": "ollama",
      "name": "Ollama lokal ($MARK)",
      "type": "ollama",
      "base_url": "http://127.0.0.1:11434/v1",
      "discover_models": false,
      "models": [
        { "id": "kontor-8b:latest", "name": "Kontor 8B (lokal)", "context_window": 16384,
          "default_max_tokens": 8192, "cost_per_1m_in": 0, "cost_per_1m_out": 0,
          "cost_per_1m_in_cached": 0, "cost_per_1m_out_cached": 0,
          "can_reason": true, "supports_attachments": true },
        { "id": "kontor-4b:latest", "name": "Kontor 4B (lokal)", "context_window": 16384,
          "default_max_tokens": 4096, "cost_per_1m_in": 0, "cost_per_1m_out": 0,
          "cost_per_1m_in_cached": 0, "cost_per_1m_out_cached": 0,
          "can_reason": true, "supports_attachments": true }
      ]
    }
  },
  "models": {
    "large": { "model": "kontor-8b:latest", "provider": "ollama", "max_tokens": 8192, "temperature": 0.3 },
    "small": { "model": "kontor-4b:latest", "provider": "ollama", "max_tokens": 4096, "temperature": 0.3 }
  },
  "mcp": {}
}
JSON
}

hosted_cfg() {
  cat <<JSON
{
  "\$schema": "https://charm.land/crush.json",
  "options": {
    "disable_default_providers": true,
    "disable_metrics": true,
    "disable_provider_auto_update": true,
    "context_paths": ["CLAUDE.md", "REPO_MANIFEST.md"]
  },
  "providers": {
    "hyper": {
      "id": "hyper",
      "name": "Charm Hyper ($MARK)",
      "type": "hyper",
      "base_url": "https://hyper.charm.land/api/v1/fantasy",
      "discover_models": false,
      "models": [
        { "id": "qwen3.8-flash", "name": "Qwen3.8 Flash (guenstig)", "context_window": 1000000,
          "default_max_tokens": 32000, "cost_per_1m_in": 0.15, "cost_per_1m_out": 0.47,
          "cost_per_1m_in_cached": 0, "cost_per_1m_out_cached": 0.016,
          "can_reason": true, "supports_attachments": true },
        { "id": "glm-5.3-flash", "name": "GLM 5.3 Flash (guenstig)", "context_window": 1048576,
          "default_max_tokens": 32000, "cost_per_1m_in": 0.16332, "cost_per_1m_out": 0.5444,
          "cost_per_1m_in_cached": 0, "cost_per_1m_out_cached": 0.0315752,
          "can_reason": true, "supports_attachments": true },
        { "id": "glm-5.3", "name": "GLM 5.3 (stark, teuer)", "context_window": 1048576,
          "default_max_tokens": 32000, "cost_per_1m_in": 1.52432, "cost_per_1m_out": 4.79072,
          "cost_per_1m_in_cached": 0, "cost_per_1m_out_cached": 0.283088,
          "can_reason": true, "supports_attachments": true }
      ]
    },
    "openrouter": {
      "id": "openrouter",
      "name": "OpenRouter free ($MARK)",
      "type": "openrouter",
      "base_url": "https://openrouter.ai/api/v1",
      "api_key": "\$(security find-generic-password -s kontor-openrouter -w)",
      "discover_models": false,
      "models": [
        { "id": "thinkingmachines/inkling:free", "name": "Inkling (free)", "context_window": 1048576,
          "default_max_tokens": 16384, "cost_per_1m_in": 0, "cost_per_1m_out": 0,
          "cost_per_1m_in_cached": 0, "cost_per_1m_out_cached": 0,
          "can_reason": true, "supports_attachments": true },
        { "id": "google/gemma-4-31b-it:free", "name": "Gemma 4 31B (free)", "context_window": 262144,
          "default_max_tokens": 8192, "cost_per_1m_in": 0, "cost_per_1m_out": 0,
          "cost_per_1m_in_cached": 0, "cost_per_1m_out_cached": 0,
          "can_reason": false, "supports_attachments": true }
      ]
    },
    "ollama": {
      "id": "ollama",
      "name": "Ollama lokal (Rueckfall)",
      "type": "ollama",
      "base_url": "http://127.0.0.1:11434/v1",
      "discover_models": false,
      "models": [
        { "id": "kontor-8b:latest", "name": "Kontor 8B (lokal)", "context_window": 16384,
          "default_max_tokens": 8192, "cost_per_1m_in": 0, "cost_per_1m_out": 0,
          "cost_per_1m_in_cached": 0, "cost_per_1m_out_cached": 0,
          "can_reason": true, "supports_attachments": true },
        { "id": "kontor-4b:latest", "name": "Kontor 4B (lokal)", "context_window": 16384,
          "default_max_tokens": 4096, "cost_per_1m_in": 0, "cost_per_1m_out": 0,
          "cost_per_1m_in_cached": 0, "cost_per_1m_out_cached": 0,
          "can_reason": true, "supports_attachments": true }
      ]
    }
  },
  "models": {
    "large": { "model": "thinkingmachines/inkling:free", "provider": "openrouter", "max_tokens": 16384 },
    "small": { "model": "google/gemma-4-31b-it:free", "provider": "openrouter", "max_tokens": 8192 }
  },
  "mcp": {
    "tavily": {
      "type": "http",
      "url": "https://mcp.tavily.com/mcp/",
      "headers": { "Authorization": "Bearer \$(security find-generic-password -s kontor-tavily -w)" },
      "enabled_tools": ["tavily_search", "tavily_extract"],
      "timeout": 60
    }
  }
}
JSON
}

check_only=0
[ "${1:-}" = "--check" ] && check_only=1
drift=0

emit() {  # emit <repo> <kind>
  local repo="$1" kind="$2" target="$HOME/$1/crush.json" want
  [ -d "$HOME/$repo" ] || { printf '  %-22s skipped (no such directory)\n' "$repo"; return; }
  if [ "$kind" = local ]; then
    local ro=no; for r in "${READONLY[@]}"; do [ "$r" = "$repo" ] && ro=yes; done
    want=$(local_cfg "$ro")
  else
    want=$(hosted_cfg)
  fi
  if [ -f "$target" ] && [ "$(cat "$target")" = "$want" ]; then
    printf '  %-22s up to date (%s)\n' "$repo" "$kind"; return
  fi
  drift=1
  if [ "$check_only" = 1 ]; then
    printf '  %-22s DRIFTED (%s)\n' "$repo" "$kind"; return
  fi
  printf '%s\n' "$want" > "$target"
  ignore_crush_json "$repo"
  printf '  %-22s written (%s)\n' "$repo" "$kind"
}

# ⚠️ qwen3-vl reasons on every turn and the OpenAI-compatible endpoint ignores
# "think": false — reasoning arrives in a separate field either way. What matters
# is that max_tokens is large enough to cover the reasoning AND the answer: with
# max_tokens 20 the content came back EMPTY and the call looked broken. The
# per-model default_max_tokens below (8192 / 4096) is the real safeguard.
#
# crush.json is machinery, not documentation: it is an output of this script, which
# is itself versioned in the manifest's canonical branch. Its history would never be read, and in a repo that
# is later shared with co-authors — drei Forschungszweigen — a personal
# tooling config naming an OpenRouter account is awkward to have committed.
# So every branch ignores it, decided once here rather than thirteen times separately.
# (Suggested by a sibling branch, 12.09.2026.)
ignore_crush_json() {
  local gi="$HOME/$1/.gitignore"
  [ -d "$HOME/$1/.git" ] || return 0
  if [ -f "$gi" ] && grep -qx 'crush.json' "$gi"; then return 0; fi
  [ -f "$gi" ] && [ -n "$(tail -c1 "$gi")" ] && printf '\n' >> "$gi"
  printf '\n# Crush-Konfiguration: generiert von tools/distribute_crush_config.sh.\n# Maschinerie, keine Dokumentation — nicht committen, nicht von Hand editieren.\ncrush.json\n' >> "$gi"
}

for r in "${LOCAL_FIRST[@]}"; do emit "$r" local;  done
for r in "${HOSTED[@]}";     do emit "$r" hosted; done

# Keep the wrapper's sandbox list in step with the classification above.
if [ "$check_only" = 0 ]; then
  mkdir -p "$(dirname "$BRANCH_LIST")"
  printf '%s\n' "${LOCAL_FIRST[@]}" > "$BRANCH_LIST"
  printf '  %-22s written (%d branches)\n' "$(basename "$BRANCH_LIST")" "${#LOCAL_FIRST[@]}"
fi

if [ "$check_only" = 1 ]; then
  [ "$drift" = 0 ] && echo "all crush configs match" || {
    echo "drift found — run without --check to overwrite" >&2; exit 1; }
fi
